version: "3"
services:
  ansibleawx:
    environment:
      TZ: Asia/Tokyo
    build: ansible/.
    container_name: ansibleawx
    volumes:
      - ./ansible/projects:/var/lib/awx/projects:rw
    privileged: true
    ports:
      - "2022:22"
      - "8080:80"
    networks:
      default:
        aliases:
          - ansibleawx.local
  raspi:
    environment:
      TZ: Asia/Tokyo
    build: raspi/.
    container_name: raspi
    ports:
      - "3022:22"
    networks:
      default:
        aliases:
          - raspi.local
