---
- name: setup samba
  hosts: all
  tasks:
    - name: install packages
      become: true
      apt:
        name:
          - samba
          - smbclient
          - samba-common-bin
        force: yes
    - name: make public dir
      file: path=/home/pi/samba/public state=directory owner=pi group=pi mode=0755
